P = ..

BOARD_TAG = oscarleo
MONITOR_PORT = /dev/leo.usb*
ARDUINO_LIBS = AdapterBoard Backlight RGBLed EEPROM Bounce2
USER_LIB_PATH = libs

ARDUINO_DIR = $P/Arduino/
ARDUINO_CORE_PATH = $P/Arduino/hardware/arduino/cores/oscar
ARDMK_DIR = $P/Arduino-Makefile
ARDMK_PATH = $P/Arduino-Makefile/bin
OPTIMIZATION_LEVEL = 3

include $P/Arduino-Makefile/Arduino.mk
