P = ../..

BOARD_TAG = leonardo
MONITOR_PORT = /dev/leo.usb*
ARDUINO_LIBS = AdapterBoard Backlight RGBLed EEPROM
USER_LIB_PATH = libs

ARDUINO_DIR = $P/Arduino/
ARDMK_DIR = $P/Arduino-Makefile
ARDMK_PATH = $P/Arduino-Makefile/bin
OPTIMIZATION_LEVEL = 3

include $P/Arduino-Makefile/Arduino.mk
